baseURL = "https://www.learngfxprogramming.cf/"
languageCode = "en-us"
title = "Learn Graphics Programming"
theme = "blackburn"
sectionPagesMenu = "main"
pygmentsUseClasses = true
pygmentsCodeFences = true
copyright = "&copy; Copyright 2018 M. Shahe Ansar"
Paginate = 10

[params]
subtitle = "A Blog where I post stuff about Graphics Programming"
disqus = "shaheansar"
custom_css = ["css/syntax.css"]
googleAnalytics = "UA-115000283-1"
[social]
gitlab = "shaheansar123323"
github = "shaheansar"

[menu]
	[[menu.main]]
	name = "Home"
	identifier = "home"
	url = "/"
	[[menu.main]]
	name = "Tutorials"
	identifier = "tutorials"
	url = "/tutorials"


